### ISSUE TITLE
Website for bot

### ISSUE THREAD

**Issue by GreenBayRules** [ParadoxalCorp/FelixBot#136]
I would like to offer my company's service to make a site for your bot that is proffesionally designed and developed. My company is the fastest and the cheapest option. Please DM me on discord if you would like to proceed. 

PackersRuleGoPack#2232

**Comment by ParadoxOrigins** [comment]
Well.

I appreciate the offer but i do not intend to have a company doing our job, nor can i afford it.

**Comment by TheFallingPie** [comment]
I would offer to make a website for ya for free, I am not a busnest so yea. It's just my plain old hobby b,

**Comment by ParadoxOrigins** [comment]
Erm well, 

I could ask some advices, but otherwise, <leak>the website is already in development</leak>

**Comment by TheFallingPie** [comment]
cool cool b. im always here, Pie#9196.

**Comment by ParadoxOrigins** [comment]
didn't you forked at some point 👀

**Comment by TheFallingPie** [comment]
no b, someone forked mine, i think internal might of.

**Comment by TheFallingPie** [comment]
o shid i did

**Comment by TheFallingPie** [comment]
but way out of date lmao

**Comment by TheFallingPie** [comment]
dont need it anyways. i delet it

**Comment by ParadoxOrigins** [comment]
*delete felix*

**Comment by TheFallingPie** [comment]
_deleted from profile_

**Comment by ParadoxOrigins** [comment]
you have some front-end design experience ?

**Comment by TheFallingPie** [comment]
ye b, thats what im mainly about, not about dat backhand kind of shiz.

**Comment by TheFallingPie** [comment]
as i said before, if ya need to contact me, my discord is Pie#9196.
