### ISSUE TITLE
why nu @Felix baguette ?!?!

### ISSUE THREAD

**Issue by Devoxin** [ParadoxalCorp/FelixBot#143]
This is honestly a shame that this command is missing and i will ensure your bot is taken down if its not added within the next 5 minutes

**Comment by Gamerein** [comment]
This guy gets it

**Comment by ParadoxOrigins** [comment]
actually look at the pull request u fkcing

**Comment by Devoxin** [comment]
accept it then big fat

**Comment by ParadoxOrigins** [comment]
DIS IS NOT OKAY

**Comment by Devoxin** [comment]
🥖

**Comment by ParadoxOrigins** [comment]
ill bean u
