### ISSUE TITLE
Issue with premium server command!

### ISSUE THREAD

**Issue by AdamAtomus** [ParadoxalCorp/FelixBot#172]
When i do felix eval guildEntry.premium = true; client.database.set(guildEntry, 'guild') --await
in my terminal it says this 
![is](https://user-images.githubusercontent.com/42122290/43689711-2655cef0-98c4-11e8-8fed-ee9e69cc27e2.PNG)

**Comment by ParadoxOrigins** [comment]
Did you ran this in your terminal? If so, that's not how you're supposed to do it, you're supposed to write that as a command in a regular discord message

**Comment by AdamAtomus** [comment]
I did, but i also tried the discord message and it didnt work

**Comment by ParadoxOrigins** [comment]
Can you detail what did you do exactly

**Comment by AdamAtomus** [comment]
I went into the general chat, then did this https://gyazo.com/33b8cd39800e178456b6573216154c4 no reply from the bot..

**Comment by ParadoxOrigins** [comment]
the link you put leads to nothing :eyes:

**Comment by AdamAtomus** [comment]
https://gyazo.com/dbf8da9d133a6218dc8e8e828fc97764

**Comment by ParadoxOrigins** [comment]
Oh, `felix` is the default prefix, if you are mentionning the bot you have to remove it, so it would become `@Bot eval ...`

**Comment by AdamAtomus** [comment]
now its saying this https://gyazo.com/e45e903bab86898d08a2bee977b345c9 when i have put me as the owner in the cfg https://gyazo.com/40dd78fd8c63edf35d3f0f3eb70f79c5

**Comment by ParadoxOrigins** [comment]
That's weird, are you sure it's your ID that you put in the config ?

**Comment by AdamAtomus** [comment]
yup! i did put the right one in,

**Comment by AdamAtomus** [comment]
Oh, fixed it
I had to put myself as an admin

**Comment by AdamAtomus** [comment]
thanks!

**Comment by AdamAtomus** [comment]
Well this happens now.... https://gyazo.com/3e1a67a593b1fe4f8a745a3d38a9b397

**Comment by ParadoxOrigins** [comment]
Did you set up a lavalink server?

**Comment by CFTheMaster** [comment]
do you have lavalink?

**Comment by AdamAtomus** [comment]
Yes, i think its the modual let me install it agian

**Comment by AdamAtomus** [comment]
https://gyazo.com/d316b1bb237588111bf96b9c1d10c70b

**Comment by ParadoxOrigins** [comment]
That's weird, is felix's config setup accordingly to the lavalink server config?

**Comment by AdamAtomus** [comment]
yes

**Comment by ParadoxOrigins** [comment]
What version of Lavalink are you running

**Comment by AdamAtomus** [comment]
https://gyazo.com/9c91252257ea647b16db018297f7d635?token=a5716ce489d7b399698d206312100bdf
/\ first yml
https://gyazo.com/655b78dcc3bd380b2789edf102be8cb1
/\ second config.js

**Comment by ParadoxOrigins** [comment]
This looks like Lavalink v3 to me, while v2 is expected

**Comment by AdamAtomus** [comment]
ok! where do i find LavaLink v2 At? as i found lava link here https://ci.fredboat.com/viewLog.html?buildId=lastSuccessful&buildTypeId=Lavalink_Build&tab=artifacts&guest=1#!

**Comment by CFTheMaster** [comment]
https://github.com/Frederikam/Lavalink/tree/v2-legacy?files=1

**Comment by AdamAtomus** [comment]
May i ask where is the jar file?

**Comment by CFTheMaster** [comment]
you have to create that yourself

**Comment by AdamAtomus** [comment]
ok! what part do i compile?

**Comment by CFTheMaster** [comment]
everything

**Comment by CFTheMaster** [comment]
http://www.skylit.com/javamethods/faqs/createjar.html
