### ISSUE TITLE
Add f!felix 

### ISSUE THREAD

**Issue by ParadoxOrigins** [ParadoxalCorp/FelixBot#26]
lets push the meme as far as possible then

**Comment by Gamerein** [comment]
https://ufile.io/rcsgm

**Comment by ParadoxOrigins** [comment]
dont post malicious file here kthx

**Comment by Gamerein** [comment]
Its not malicious lol. Thats the download for the zip file. tested it myself is safe

**Comment by Gamerein** [comment]
No promises tho

**Comment by ParadoxOrigins** [comment]
use imgur's api for that as well

**Comment by ParadoxOrigins** [comment]
discretely removing that from the 1.2.3 and planning it to the 1.3.3 since im not motivated enough lul

**Comment by ParadoxOrigins** [comment]
Referenced in #103
